meta_product_name: "FreshCollect"
meta_title: "FreshCollect - join our community and reduce food waste today!"
meta_description: "Welcome to FreshCollect - we help you share your leftover groceries with neighbors to minimize food waste."
meta_image: "cover.jpg"
